name: deploy web

on: push

jobs:
  deploy_website:
    runs-on: ubuntu-20.04
    steps:
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd web
          echo "VUE_APP_PAGE_TITLE=Easy-to-Use Online MQTT Client | Try Now" > .env.local
          echo "VUE_APP_PAGE_DESCRIPTION=Online MQTT 5.0 client on the web, using MQTT over WebSocket to connect to the MQTT Broker and test message publishing and receiving in the browser." >> .env.local

      - name: build
        run: |
          cd web
          yarn && yarn build
